server:
  port: 8090

#Database info
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Pruebasconjava
    url: jdbc:mysql://db4free.net/dbpersonas9876?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true
    username: pruebasenmicrud
    
#Hibernate ddl auto (create, create-drop, validate, update)    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect